/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Logic.Contact;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import javax.swing.JOptionPane;
import java.util.*;

/**
 * @author: Daniel Lozano
 *
 */
public class GUI extends javax.swing.JFrame {

    int contactCount = 0;
    ArrayList<Contact> ContactList = new ArrayList<>();

    /**
     * Creates new form Student
     */
    public GUI() {
        initComponents();
        Inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGénero = new javax.swing.ButtonGroup();
        addContactPane = new javax.swing.JPanel();
        lblNombreE = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccióm = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        JtxtName = new javax.swing.JTextField();
        JtxtLastName = new javax.swing.JTextField();
        JtxtPhone = new javax.swing.JTextField();
        JtxtAdress = new javax.swing.JTextField();
        JtxtMail = new javax.swing.JTextField();
        btnSaveStudent = new javax.swing.JButton();
        JbtnSearchStudent = new javax.swing.JButton();
        JbtnModifyStudent = new javax.swing.JButton();
        DisplayPane = new javax.swing.JPanel();
        ContactListPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JtxtAreaReport = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addContactPane.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTACTO"));

        lblNombreE.setText("NOMBRE:");

        lblApellido.setText("APELLIDO:");

        lblTelefono.setText("TELÉFONO:");

        lblDireccióm.setText("DIRECCIÓN:");

        lblCorreo.setText("CORREO:");

        JtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtNameActionPerformed(evt);
            }
        });
        JtxtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtNameKeyTyped(evt);
            }
        });

        JtxtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtLastNameKeyTyped(evt);
            }
        });

        JtxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtPhoneActionPerformed(evt);
            }
        });
        JtxtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtxtPhoneKeyTyped(evt);
            }
        });

        JtxtAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtAdressActionPerformed(evt);
            }
        });

        btnSaveStudent.setText("Guardar");
        btnSaveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStudentActionPerformed(evt);
            }
        });

        JbtnSearchStudent.setText("Buscar");
        JbtnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSearchStudentActionPerformed(evt);
            }
        });

        JbtnModifyStudent.setText("Modificar");
        JbtnModifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnModifyStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addContactPaneLayout = new javax.swing.GroupLayout(addContactPane);
        addContactPane.setLayout(addContactPaneLayout);
        addContactPaneLayout.setHorizontalGroup(
            addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addContactPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addContactPaneLayout.createSequentialGroup()
                        .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreE)
                            .addComponent(JbtnSearchStudent)
                            .addComponent(lblDireccióm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addContactPaneLayout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JtxtLastName)
                                        .addComponent(JtxtName)
                                        .addComponent(JtxtPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JtxtAdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40))
                            .addGroup(addContactPaneLayout.createSequentialGroup()
                                .addComponent(JbtnModifyStudent)
                                .addGap(18, 18, 18)
                                .addComponent(btnSaveStudent)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addContactPaneLayout.createSequentialGroup()
                        .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellido)
                            .addComponent(lblTelefono)
                            .addComponent(lblCorreo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addContactPaneLayout.setVerticalGroup(
            addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addContactPaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(JtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccióm)
                    .addComponent(JtxtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(JtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(addContactPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveStudent)
                    .addComponent(JbtnSearchStudent)
                    .addComponent(JbtnModifyStudent))
                .addGap(35, 35, 35))
        );

        DisplayPane.setBorder(javax.swing.BorderFactory.createTitledBorder("VER EL CONTACTO"));

        javax.swing.GroupLayout DisplayPaneLayout = new javax.swing.GroupLayout(DisplayPane);
        DisplayPane.setLayout(DisplayPaneLayout);
        DisplayPaneLayout.setHorizontalGroup(
            DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        DisplayPaneLayout.setVerticalGroup(
            DisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        ContactListPane.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTA DE CONTACTOS"));

        JtxtAreaReport.setColumns(20);
        JtxtAreaReport.setRows(5);
        jScrollPane3.setViewportView(JtxtAreaReport);

        javax.swing.GroupLayout ContactListPaneLayout = new javax.swing.GroupLayout(ContactListPane);
        ContactListPane.setLayout(ContactListPaneLayout);
        ContactListPaneLayout.setHorizontalGroup(
            ContactListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactListPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        ContactListPaneLayout.setVerticalGroup(
            ContactListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactListPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExit.setText("SALIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addContactPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DisplayPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContactListPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactListPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addContactPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ContactListPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStudentActionPerformed
        // TODO add your handling code here:

        String emailRegex = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        String mail = JtxtMail.getText();

        if (!mail.matches(emailRegex)) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un mail válido.");
        } else if (JtxtPhone.getText().length() != 10) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un teléfono válido de 10 dígitos.");
        } else if (JtxtName.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un nombre.");
        } else if (JtxtLastName.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Por favor digite un apellido.");
        } else if (JtxtAdress.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Por favor digite una dirección.");
        } else {
            // TODO: Save Contact
            cleanFields();
            try{
            SaveContact();
            }catch(Exception e){
                e.getMessage();
            }
        }
    }//GEN-LAST:event_btnSaveStudentActionPerformed

    private void JtxtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtAdressActionPerformed

    private void JtxtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtPhoneKeyTyped
        int limit = 10;
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            if (JtxtPhone.getText().length() >= limit) {
                evt.consume();
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_JtxtPhoneKeyTyped

    private void JtxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtPhoneActionPerformed

    private void JtxtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtLastNameKeyTyped
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            getToolkit().beep();
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_JtxtLastNameKeyTyped

    private void JtxtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtxtNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            getToolkit().beep();
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_JtxtNameKeyTyped

    private void JtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtNameActionPerformed

    private void JbtnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSearchStudentActionPerformed
        // TODO add your handling code here:
        //JdialogSearch.setVisible(true);

        long code = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el telefono del contacto a buscar"));
        Contact SearchContact = new Contact();
        int index = SearchContact.searchContact(code, ContactList);
        System.out.println(index);
        if (index != -1) {
            generateReport(index);
        } else {
            JOptionPane.showConfirmDialog(null, "El contácto no existe.");
        }

    }//GEN-LAST:event_JbtnSearchStudentActionPerformed

    private void JbtnModifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnModifyStudentActionPerformed
        // TODO add your handling code here:
        int code = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el telefono del contacto a modificar"));
        int index = getIndex(code);
        if (index != -1) {
            generateReport(index);
        } else {
            JOptionPane.showConfirmDialog(null, "El estudiante no existe.");
        }

    }//GEN-LAST:event_JbtnModifyStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContactListPane;
    private javax.swing.JPanel DisplayPane;
    private javax.swing.JButton JbtnModifyStudent;
    private javax.swing.JButton JbtnSearchStudent;
    private javax.swing.JTextField JtxtAdress;
    private javax.swing.JTextArea JtxtAreaReport;
    private javax.swing.JTextField JtxtLastName;
    private javax.swing.JTextField JtxtMail;
    private javax.swing.JTextField JtxtName;
    private javax.swing.JTextField JtxtPhone;
    private javax.swing.JPanel addContactPane;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSaveStudent;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccióm;
    private javax.swing.JLabel lblNombreE;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.ButtonGroup rbtnGénero;
    // End of variables declaration//GEN-END:variables

    private void Inicializar() {
        cleanFields();
        
    }

    public void SaveContact() throws FileNotFoundException, UnsupportedEncodingException {

        Contact CurrentContact = new Contact();
        long phone = Long.parseLong(JtxtPhone.getText());
        String adress = JtxtAdress.getText();
        String name = JtxtName.getText();
        String lastName = JtxtLastName.getText();
        String mail = JtxtMail.getText();

        // Setters declaration
        CurrentContact.setName(name);
        CurrentContact.setLastName(lastName);
        CurrentContact.setPhone(phone);
        CurrentContact.setAdress(adress);
        CurrentContact.setMail(mail);

        boolean exists = false;
        // TODO: 
        if (exists == false) {
            ContactList.add(contactCount, CurrentContact);
            contactCount++;
            CurrentContact.writeFile(ContactList);
        } else {
            JOptionPane.showConfirmDialog(null, "El contacto ya existe.");
        }
        

    }

    public void cleanFields() {

        JtxtName.setText("");
        JtxtLastName.setText("");
        JtxtAdress.setText("");
        JtxtMail.setText("nombre@tu-correo.com");
        JtxtPhone.setText("");

    }

    public int getIndex(long code) {
        Contact StudentIndex = new Contact();
        int query = StudentIndex.searchContact(code, ContactList);
        return query;
    }

    public void generateReport(int index) {
        //JdialogReport.setVisible(true);
        Contact ContactReport = ContactList.get(index);
        String name = ContactReport.getName();
        String lastName = ContactReport.getLastName();
        Long phone = ContactReport.getPhone();
        String adress = ContactReport.getAdress();
        String mail = ContactReport.getMail();

        //Populate TextField
        JtxtAreaReport.setText("Nombre:" + name + "\nApellido: " + lastName + "\nDirección: " + adress + "\nCorreo: " + mail + "\nGénero: ");
    }

}
